from PySide6.QtWidgets import QWidget, QVBoxLayout, QHBoxLayout, QLabel, QTableWidget, QTableWidgetItem, QHeaderView, QPushButton, QMessageBox, QFrame, QAbstractItemView
from PySide6.QtCore import Qt, QDateTime
from PySide6.QtCharts import QChart, QChartView, QPieSeries, QLineSeries, QDateTimeAxis, QValueAxis
from datetime import datetime
from database.database import Database
class DashboardPage(QWidget):
    def __init__(self):
        super().__init__()
        self.db = Database()
        self._setup_ui()
        self.refresh_dashboard()
    def _setup_ui(self):
        main_layout = QVBoxLayout()
        header_layout = QHBoxLayout()
        title_label = QLabel("Dashboard")
        title_label.setStyleSheet("font-size : 18px; font-weight : bold;")
        self.refresh_button = QPushButton("Refresh")
        self.refresh_button.clicked.connect(self.refresh_dashboard)
        header_layout.addWidget(title_label)
        header_layout.addStretch()
        header_layout.addWidget(self.refresh_button)
        main_layout.addLayout(header_layout)
        separator = QFrame()
        separator.setFrameShape(QFrame.Shape.HLine)
        separator.setFrameShadow(QFrame.Shadow.Sunken)
        main_layout.addWidget(separator)
        self.summary_title_label = QLabel("")
        self.summary_title_label.setStyleSheet("font-size : 14px; font-weight : bold;")
        main_layout.addWidget(self.summary_title_label)
        self.income_label = QLabel("Income: 0.00")
        self.expense_label = QLabel("Expenses: 0.00")
        self.balance_label = QLabel("Net Balance: 0.00")
        for label in (self.income_label, self.expense_label, self.balance_label):
            label.setAlignment(Qt.AlignmentFlag.AlignLeft)
            label.setStyleSheet("font-size : 13px; font-weight : bold;")
        main_layout.addWidget(self.income_label)
        main_layout.addWidget(self.expense_label)
        main_layout.addWidget(self.balance_label)
        main_layout.addSpacing(10)
        top_cat_title = QLabel("Top Expense Categories (This Month)")
        top_cat_title.setStyleSheet("font-size : 13px; font-weight : bold;")
        main_layout.addWidget(top_cat_title)
        self.top_categories_table = QTableWidget()
        self.top_categories_table.setColumnCount(2)
        self.top_categories_table.setHorizontalHeaderLabels(["Category", "Total Amount"])
        self.top_categories_table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Stretch)
        self.top_categories_table.verticalHeader().setVisible(False)
        self.top_categories_table.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
        self.top_categories_table.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        main_layout.addWidget(self.top_categories_table)
        main_layout.addSpacing(10)
        recent_title = QLabel("Recent Transactions")
        recent_title.setStyleSheet("font-size : 13px; font-weight : bold;")
        main_layout.addWidget(recent_title)
        self.recent_table = QTableWidget()
        self.recent_table.setColumnCount(4)
        self.recent_table.setHorizontalHeaderLabels(["Date", "Type", "Category", "Amount"])
        self.recent_table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Stretch)
        self.recent_table.verticalHeader().setVisible(False)
        self.recent_table.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
        self.recent_table.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        main_layout.addWidget(self.recent_table)
        chart_title = QLabel("Spending Analytics")
        chart_title.setStyleSheet("font-size : 13px; font-weight : bold;")
        main_layout.addWidget(chart_title)
        self.category_chart_view = QChartView()
        self.subcategory_chart_view = QChartView()
        self.trend_chart_view = QChartView()
        main_layout.addWidget(self.category_chart_view)
        main_layout.addWidget(self.subcategory_chart_view)
        main_layout.addWidget(self.trend_chart_view)
        self.setLayout(main_layout)
    def load_category_chart(self, year, month):
        stats = self.db.get_category_stats(year, month)
        if not stats:
            chart = QChart()
            chart.setTitle("No data for this month")
            self.category_chart_view.setChart(chart)
            return
        series = QPieSeries()
        for category, total in stats.items():
            series.append(category, total)
        chart = QChart()
        chart.addSeries(series)
        chart.setTitle("Expense Breakdown by Category")
        chart.legend().setVisible(True)
        for slice in series.slices():
            category_name = slice.label()
            percent = (slice.percentage() * 100)
            slice.setLabel(f"{category_name} ({percent:.1f}%)")
            slice.clicked.connect(lambda checked=False, c=category_name : self.load_subcategory_chart(year, month, c))
        self.category_chart_view.setChart(chart)
    def load_subcategory_chart(self, year, month, category):
        stats = self.db.get_subcategory_stats(year, month, category)
        series = QPieSeries()
        for subcat, total in stats.items():
            name = subcat if subcat else "Other"
            series.append(name, total)
        chart = QChart()
        chart.addSeries(series)
        chart.setTitle(f"Subcategories of {category}")
        chart.legend().setVisible(True)
        self.subcategory_chart_view.setChart(chart)
    def load_trend_chart(self, year, month):
        points = self.db.get_daily_expenses(year, month)
        series = QLineSeries()
        for date_str, total in points:
            dt = datetime.strptime(date_str, "%Y-%m-%d")
            timestamp = int(dt.timestamp() * 1000)
            series.append(timestamp, total)
        chart = QChart()
        chart.addSeries(series)
        chart.setTitle("Daily Expense Trend")
        axis_x = QDateTimeAxis()
        axis_x.setFormat("dd MMM")
        axis_x.setTitleText("Date")
        axis_y = QValueAxis()
        axis_y.setTitleText("Amount")
        if points:
            first_dt = datetime.strptime(points[0][0], "%Y-%m-%d")
            last_dt = datetime.strptime(points[-1][0], "%Y-%m-%d")
            axis_x.setMin(QDateTime.fromMSecsSinceEpoch(int(first_dt.timestamp() * 1000)))
            axis_x.setMax(QDateTime.fromMSecsSinceEpoch(int(last_dt.timestamp() * 1000)))
            totals = [total for _, total in points]
            min_val = min(totals)
            max_val = max(totals)
            axis_y.setRange(min_val * 0.9, max_val * 1.1)
        else:
            chart.setTitle("No data for this month")
        chart.addAxis(axis_x, Qt.AlignmentFlag.AlignBottom)
        chart.addAxis(axis_y, Qt.AlignmentFlag.AlignLeft)
        series.attachAxis(axis_x)
        series.attachAxis(axis_y)
        self.trend_chart_view.setChart(chart)
    def refresh_dashboard(self):
        try:
            now = datetime.now()
            year = str(now.year)
            month = f"{now.month:02d}"
            month_name = now.strftime("%B")
            self.summary_title_label.setText(f"Summary for {month_name} {year}")
            summary = self.db.get_month_summary(year,month)
            income = summary.get("income",0)
            expenses = summary.get("expense",0)
            balance = income - expenses
            self.income_label.setText(f"Income: {income:.2f}")
            self.expense_label.setText(f"Expenses: {expenses:.2f}")
            self.balance_label.setText(f"Net Balance: {balance:.2f}")
            cat_stats = self.db.get_category_stats(year, month)
            top_cats = sorted(cat_stats.items(), key = lambda x: x[1], reverse=True)[:3]
            self.top_categories_table.setRowCount(len(top_cats))
            for row_idx, (category, total) in enumerate(top_cats):
                self.top_categories_table.setItem(row_idx, 0, QTableWidgetItem(category))
                self.top_categories_table.setItem(row_idx, 1, QTableWidgetItem(f"{total:.2f}"))
            all_transactions = self.db.get_all_transactions()
            recent = sorted(all_transactions, key = lambda t: t.date, reverse=True)[:5]
            self.recent_table.setRowCount(len(recent))
            for row_idx,trans in enumerate(recent):
                self.recent_table.setItem(row_idx, 0, QTableWidgetItem(str(trans.date)))
                self.recent_table.setItem(row_idx, 1, QTableWidgetItem(trans.type))
                self.recent_table.setItem(row_idx, 2, QTableWidgetItem(trans.category))
                self.recent_table.setItem(row_idx, 3, QTableWidgetItem(f"{trans.amount:.2f}"))
            self.load_category_chart(year, month)
            self.load_trend_chart(year, month)
            chart = QChart()
            chart.setTitle("Click a category to see subcategories")
            self.subcategory_chart_view.setChart(chart)
        except Exception as e:
            QMessageBox.critical(self, "Error", f"Failed to load dashboard.\n{e}")

